import Img01 from '@/assets/images/beyond-class-main-cover-01.png';
import Img02 from '@/assets/images/beyond-class-main-cover-02.png';
import Img03 from '@/assets/images/beyond-class-main-cover-03.png';
import Img04 from '@/assets/images/beyond-class-main-cover-04.png';
import Img05 from '@/assets/images/beyond-class-main-cover-05.png';
import Img06 from '@/assets/images/beyond-class-main-cover-06.png';
import Img07 from '@/assets/images/beyond-class-main-cover-07.png';
import Img08 from '@/assets/images/beyond-class-main-cover-08.png';

import Img09 from '@/assets/images/basic-class-main-cover-01.png';
import Img10 from '@/assets/images/basic-class-main-cover-02.png';
import Img11 from '@/assets/images/basic-class-main-cover-03.png';
import Img12 from '@/assets/images/basic-class-main-cover-04.png';
import Img13 from '@/assets/images/basic-class-main-cover-05.png';
import Img14 from '@/assets/images/basic-class-main-cover-06.png';
import Img15 from '@/assets/images/basic-class-main-cover-07.png';
import Img16 from '@/assets/images/basic-class-main-cover-08.png';

export const headers = [
  {
    title: '강의 그 이상의 인사이트',
    link: '#one',
    buttonText: '전체 클래스 보기',
  },
];

export const classes1 = [
  {
    id: 1,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img01,
    link: '/html/class-detail.html',
  },
  {
    id: 2,
    title: '아름답고 탄탄한 라인을 만들어주는 필라테스 클래스',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 5.0,
    students: 1234,
    img: Img02,
    link: '/html/class-detail.html',
  },
  {
    id: 3,
    title: '외국인과 영어로 대화하는 노하우! 영어 발음 배우기',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img03,
    link: '/html/class-detail.html',
  },
  {
    id: 4,
    title: '내 집 마련의 꿈을 꿈이 아닌 현실로 만드는 진짜 방법',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img04,
    link: '/html/class-detail.html',
  },
  {
    id: 5,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img05,
    link: '/html/class-detail.html',
  },
  {
    id: 6,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img06,
    link: '/html/class-detail.html',
  },
  {
    id: 7,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img07,
    link: '/html/class-detail.html',
  },
  {
    id: 8,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img08,
    link: '/html/class-detail.html',
  },
];

export const classes2 = [
  {
    id: 1,
    title: '월 500만원 매출을 내는 블로그 운영하는 노하우',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img09,
    link: '/html/class-detail.html',
  },
  {
    id: 2,
    title: '눈으로 보는 색감을 그대로, 성공하는 촬영법과 감성 보정',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img10,
    link: '/html/class-detail.html',
  },
  {
    id: 3,
    title: '퍼블리셔를 위한 필수! 퍼블리셔 취업 진짜 실전 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img11,
    link: '/html/class-detail.html',
  },
  {
    id: 4,
    title: '모바일 웹 퍼블리싱 포트폴리오 with Figma',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img12,
    link: '/html/class-detail.html',
  },
  {
    id: 5,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img13,
    link: '/html/class-detail.html',
  },
  {
    id: 6,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img14,
    link: '/html/class-detail.html',
  },
  {
    id: 7,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img15,
    link: '/html/class-detail.html',
  },
  {
    id: 8,
    title: '[2022년 출제기준] 웹디자인기능사 실기시험 완벽 가이드',
    instructor: '코딩웍스',
    lectures: 80,
    duration: '16시간 30분',
    pricePrev: 132000,
    priceCurrent: 92400,
    rating: 4.9,
    students: 1234,
    img: Img16,
    link: '/html/class-detail.html',
  },
];
